# Generated by Django 6.0.1 on 2026-01-17 04:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('account_type', models.CharField(choices=[('A', 'Activo'), ('P', 'Pasivo'), ('C', 'Capital'), ('I', 'Ingresos'), ('G', 'Gastos'), ('K', 'Costos')], max_length=1)),
                ('level', models.IntegerField(default=1)),
                ('is_selectable', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.account')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Nombre del Banco')),
                ('account_number', models.CharField(max_length=50, verbose_name='Número de Cuenta')),
                ('currency', models.CharField(default='GTQ', max_length=3, verbose_name='Moneda')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo Actual')),
                ('accounting_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.account', verbose_name='Cuenta Contable')),
            ],
        ),
        migrations.CreateModel(
            name='BankMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('movement_type', models.CharField(choices=[('IN', 'Depósito'), ('OUT', 'Retiro/Cheque')], max_length=3)),
                ('category', models.CharField(default='General', max_length=50)),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia / No. Cheque')),
                ('evidence', models.ImageField(blank=True, null=True, upload_to='bank_movements/', verbose_name='Comprobante')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='core.bankaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la Empresa')),
                ('nit', models.CharField(default='CF', max_length=20, verbose_name='NIT')),
                ('tax_id', models.CharField(max_length=20, unique=True, verbose_name='Identificación Fiscal')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección Legal')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='BusinessPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Razón Social / Nombre')),
                ('tax_id', models.CharField(max_length=20, verbose_name='NIT')),
                ('nit', models.CharField(blank=True, max_length=20, null=True, verbose_name='NIT (Opcional)')),
                ('type', models.CharField(choices=[('C', 'Cliente'), ('P', 'Proveedor'), ('A', 'Ambos')], default='CLIENTE', max_length=10, verbose_name='Tipo Texto')),
                ('partner_type', models.CharField(choices=[('C', 'Cliente'), ('P', 'Proveedor'), ('A', 'Ambos')], default='P', max_length=1, verbose_name='Tipo Código')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco del Proveedor')),
                ('bank_account', models.CharField(blank=True, max_length=50, null=True, verbose_name='No. Cuenta Proveedor')),
                ('account_type', models.CharField(blank=True, default='Monetaria', max_length=50, null=True, verbose_name='Tipo Cuenta')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Sucursal')),
                ('code', models.CharField(max_length=10, verbose_name='Código')),
                ('location', models.CharField(max_length=255, verbose_name='Ubicación')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='core.company')),
            ],
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.AddField(
            model_name='account',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('dpi', models.CharField(blank=True, max_length=20, verbose_name='DPI')),
                ('nit', models.CharField(blank=True, max_length=20, verbose_name='NIT')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('position', models.CharField(max_length=100, verbose_name='Cargo / Puesto')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('date_hired', models.DateField(verbose_name='Fecha de Contratación')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario Base (Q)')),
                ('bonus', models.DecimalField(decimal_places=2, default=250.0, max_digits=10, verbose_name='Bonificación Decreto')),
                ('igss_number', models.CharField(blank=True, max_length=20, verbose_name='No. Afiliación IGSS')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_employees', to='core.company')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Sistema')),
            ],
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Factura')),
                ('proveedor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Proveedor')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='gastos/', verbose_name='Factura')),
                ('serie', models.CharField(blank=True, max_length=50, null=True)),
                ('no_factura', models.CharField(blank=True, max_length=50, null=True)),
                ('nit_emisor', models.CharField(blank=True, max_length=20, null=True)),
                ('nombre_emisor', models.CharField(blank=True, max_length=200, null=True)),
                ('concepto', models.TextField(blank=True, null=True)),
                ('base_imponible', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impuesto_iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impuesto_idp', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tipo_gasto', models.CharField(default='GENERAL', max_length=20)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('placa_vehiculo', models.CharField(blank=True, max_length=20, null=True)),
                ('ocr_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='core.account', verbose_name='Cuenta Contable (NIC/NIIF)')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bankaccount', verbose_name='Cuenta de Pago')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('usuario_registra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('description', models.CharField(max_length=200, verbose_name='Descripción / Cliente')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Total')),
                ('reference_doc', models.CharField(blank=True, max_length=50, verbose_name='No. Factura/Recibo')),
                ('evidence', models.ImageField(blank=True, null=True, upload_to='incomes/', verbose_name='Comprobante')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bankaccount', verbose_name='Cuenta Destino')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Préstamo')),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cuota Mensual')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo Pendiente')),
                ('reason', models.CharField(max_length=200, verbose_name='Motivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee', verbose_name='Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='Mes')),
                ('year', models.IntegerField(verbose_name='Año')),
                ('date_generated', models.DateField(auto_now_add=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_closed', models.BooleanField(default=False, verbose_name='Cerrada')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_payrolls', to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='PayrollDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, max_digits=10)),
                ('igss_deduction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('isr_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.payroll')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('sku', models.CharField(max_length=50, verbose_name='SKU / Código Interno')),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Barras (Escáner)')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Costo Promedio')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Venta')),
                ('stock', models.IntegerField(default=0, verbose_name='Existencia Actual')),
                ('min_stock', models.IntegerField(default=5, verbose_name='Stock Mínimo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Foto del Producto')),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_products', to='core.company')),
            ],
            options={
                'unique_together': {('company', 'sku')},
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Entrada (Compra/Ajuste)'), ('OUT', 'Salida (Venta/Consumo)')], max_length=3, verbose_name='Tipo')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Unitario (Q)')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Costo Total')),
                ('reference', models.CharField(max_length=100, verbose_name='Referencia (Fac/Vale)')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_movements', to='core.company')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='core_movement_users', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Producto')),
            ],
        ),
        migrations.CreateModel(
            name='UserRoleCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'role', 'company')},
            },
        ),
        migrations.AddField(
            model_name='company',
            name='users',
            field=models.ManyToManyField(related_name='companies_assigned', through='core.UserRoleCompany', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Bodega')),
                ('is_main', models.BooleanField(default=False, verbose_name='¿Principal?')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='core.branch')),
            ],
        ),
    ]
