# Generated by Django 6.0.1 on 2026-01-17 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='amount_untaxed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Base (Sin IVA)'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IVA Crédito'),
        ),
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=20, unique=True, verbose_name='Placa')),
                ('brand', models.CharField(max_length=50, verbose_name='Marca')),
                ('model', models.CharField(max_length=50, verbose_name='Modelo')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Año')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Empresa')),
            ],
        ),
        migrations.AddField(
            model_name='gasto',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fleet', verbose_name='Vehículo / Placa'),
        ),
    ]
