# Generated by Django 5.2.10 on 2026-01-30 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_gasto_amount_untaxed_gasto_iva_fleet_gasto_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('movement_type', models.CharField(choices=[('IN', 'Entrada / Depósito'), ('OUT', 'Salida / Retiro')], default='OUT', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia')),
                ('evidence', models.ImageField(blank=True, null=True, upload_to='bank_evidence/', verbose_name='Comprobante')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bankaccount')),
            ],
        ),
    ]
