# Generated by Django 5.0.2 on 2026-02-11 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_journalitem_account_and_more'),
        ('sales', '0002_remove_payment_invoice_remove_invoice_customer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessPartner',
        ),
        migrations.DeleteModel(
            name='CreditCard',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='InventoryMovement',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceDetail',
        ),
        migrations.DeleteModel(
            name='JournalEntry',
        ),
        migrations.DeleteModel(
            name='JournalItem',
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
        migrations.DeleteModel(
            name='Payroll',
        ),
        migrations.DeleteModel(
            name='PayrollDetail',
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.DeleteModel(
            name='PurchaseDetail',
        ),
        migrations.DeleteModel(
            name='Quotation',
        ),
        migrations.DeleteModel(
            name='QuotationDetail',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='SaleDetail',
        ),
        migrations.DeleteModel(
            name='StockMovement',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
