# Generated by Django 6.0.1 on 2026-01-31 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_journalentry_journalitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Razón Social / Nombre')),
                ('nit', models.CharField(max_length=20, unique=True, verbose_name='NIT')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Dirección Fiscal')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Facturación')),
                ('contact_name', models.CharField(blank=True, max_length=100, verbose_name='Nombre de Contacto')),
                ('credit_days', models.IntegerField(default=0, verbose_name='Días de Crédito')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Límite de Crédito')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
    ]
