# Generated by Django 5.0.2 on 2026-02-01 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sale_saledetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Razón Social / Nombre')),
                ('nit', models.CharField(blank=True, max_length=20, verbose_name='NIT')),
                ('contact_name', models.CharField(blank=True, max_length=100, verbose_name='Contacto')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.companyprofile', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha de Compra')),
                ('reference', models.CharField(blank=True, max_length=50, verbose_name='No. Factura Proveedor')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Compra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.companyprofile', verbose_name='Empresa')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.provider', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
            },
        ),
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Producto')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='core.purchase')),
            ],
        ),
    ]
