# Generated by Django 5.0.2 on 2026-02-01 22:50

import django.db.models.deletion
from django.db import migrations, models
from django.db import connection # <--- AGREGUE ESTE

def limpiar_fantasmas(apps, schema_editor):
    with connection.cursor() as cursor:
        # PASO 1: Borrar de la tabla 'core_banktransaction' (La que dio error ahorita)
        cursor.execute("""
            DELETE FROM core_banktransaction 
            WHERE account_id IN (
                SELECT id FROM core_bankaccount WHERE company_id = 2
            );
        """)

        # PASO 2: Borrar de la tabla 'core_bankmovement' (La que dio error antes, por si acaso)
        # Usamos un bloque TRY/CATCH en SQL por si la tabla no existe, para que no falle
        try:
            cursor.execute("""
                DELETE FROM core_bankmovement 
                WHERE account_id IN (
                    SELECT id FROM core_bankaccount WHERE company_id = 2
                );
            """)
        except:
            pass # Si la tabla no existe, ignoramos el error

        # PASO 3: Ahora sí, borrar la CUENTA PADRE
        cursor.execute("DELETE FROM core_bankaccount WHERE company_id = 2;")

class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('core', '0010_provider_purchase_purchasedetail'),
    ]

    operations = [
        migrations.RunPython(limpiar_fantasmas),
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'verbose_name': 'Cuenta Bancaria', 'verbose_name_plural': 'Cuentas Bancarias'},
        ),
        migrations.RenameField(
            model_name='bankaccount',
            old_name='current_balance',
            new_name='balance',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='accounting_account',
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(max_length=50, verbose_name='Nombre del Banco'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.companyprofile', verbose_name='Empresa'),
        ),
    ]
