# Generated by Django 5.0.2 on 2026-02-01 22:50

import django.db.models.deletion
from django.db import migrations, models
from django.db import connection # <--- AGREGUE ESTE

def limpiar_fantasmas(apps, schema_editor):
    with connection.cursor() as cursor:
        # PASO 1: Borrar los MOVIMIENTOS (Hijos) de esas cuentas huérfanas
        # Buscamos los movimientos donde la cuenta pertenezca a la empresa 2
        cursor.execute("""
            DELETE FROM core_bankmovement 
            WHERE account_id IN (
                SELECT id FROM core_bankaccount WHERE company_id = 2
            );
        """)

        # PASO 2: Ahora sí, borrar la CUENTA (Padre)
        cursor.execute("DELETE FROM core_bankaccount WHERE company_id = 2;")

class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('core', '0010_provider_purchase_purchasedetail'),
    ]

    operations = [
        migrations.RunPython(limpiar_fantasmas),
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'verbose_name': 'Cuenta Bancaria', 'verbose_name_plural': 'Cuentas Bancarias'},
        ),
        migrations.RenameField(
            model_name='bankaccount',
            old_name='current_balance',
            new_name='balance',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='accounting_account',
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(max_length=50, verbose_name='Nombre del Banco'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.companyprofile', verbose_name='Empresa'),
        ),
    ]
