# Generated by Django 5.0.2 on 2026-02-04 02:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_quotation_payment_method_alter_quotation_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyprofile',
            options={},
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='website',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, help_text='Seleccione los usuarios que pueden acceder a esta empresa.', related_name='allowed_companies', to=settings.AUTH_USER_MODEL, verbose_name='Usuarios Autorizados'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre de la Empresa'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='nit',
            field=models.CharField(max_length=20, verbose_name='NIT'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
    ]
