# Generated by Django 5.0.2 on 2026-02-04 05:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_companyprofile_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasedetail',
            old_name='cost_price',
            new_name='unit_cost',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='reference',
        ),
        migrations.AddField(
            model_name='purchase',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='document_reference',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='No. Factura Proveedor'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('RECEIVED', 'Recibido / Inventario Cargado'), ('CANCELLED', 'Cancelada')], default='RECEIVED', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Comprador'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Compra'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Razón Social / Nombre')),
                ('nit', models.CharField(blank=True, max_length=20, null=True, verbose_name='NIT / RUT')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('contact_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de Contacto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.companyprofile', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.supplier', verbose_name='Proveedor'),
        ),
    ]
