# Generated by Django 5.0.2 on 2026-02-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_cost_price_purchasedetail_unit_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Efectivo'), ('TRANSFER', 'Transferencia Bancaria'), ('CARD', 'Tarjeta de Crédito/Débito'), ('CHECK', 'Cheque'), ('CREDIT', 'Crédito (Por Pagar)')], default='CASH', max_length=20, verbose_name='Método de Pago'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Ej: Banco Industrial, Tarjeta terminación 4099', max_length=100, null=True, verbose_name='Cuenta / Referencia / Tarjeta'),
        ),
    ]
