# Generated by Django 5.0.2 on 2026-02-04 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_purchase_payment_method_purchase_payment_reference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Sucursal', 'verbose_name_plural': 'Sucursales'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'Bodega', 'verbose_name_plural': 'Bodegas'},
        ),
        migrations.RemoveField(
            model_name='branch',
            name='location',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='is_main',
        ),
        migrations.AddField(
            model_name='branch',
            name='address',
            field=models.CharField(default=0, max_length=200, verbose_name='Dirección'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.warehouse', verbose_name='Bodega de Entrada'),
        ),
        migrations.AddField(
            model_name='sale',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch', verbose_name='Sucursal de Facturación'),
        ),
        migrations.AddField(
            model_name='sale',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.warehouse', verbose_name='Bodega de Despacho'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.CharField(help_text='Ej: Z9, CENT, SUR', max_length=20, verbose_name='Código/Prefijo'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.companyprofile', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre Sucursal'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='core.branch', verbose_name='Sucursal'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre Bodega'),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Existencia Actual')),
                ('min_stock', models.IntegerField(default=5, verbose_name='Stock Mínimo en esta Bodega')),
                ('location', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ubicación/Estante')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Producto')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.warehouse', verbose_name='Bodega')),
            ],
            options={
                'verbose_name': 'Inventario por Bodega',
                'verbose_name_plural': 'Inventarios por Bodega',
                'unique_together': {('warehouse', 'product')},
            },
        ),
    ]
