# Generated by Django 5.0.2 on 2026-02-04 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_branch_options_alter_warehouse_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('movement_type', models.CharField(choices=[('IN_PURCHASE', 'Entrada por Compra'), ('OUT_SALE', 'Salida por Venta'), ('TRANSFER_OUT', 'Salida por Traslado'), ('TRANSFER_IN', 'Entrada por Traslado'), ('ADJUST_ADD', 'Ajuste (Entrada)'), ('ADJUST_SUB', 'Ajuste (Salida)')], max_length=20, verbose_name='Tipo de Movimiento')),
                ('related_transfer_id', models.IntegerField(blank=True, help_text='ID del grupo de traslado', null=True)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('comments', models.CharField(blank=True, max_length=200, null=True, verbose_name='Comentario/Razón')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Producto')),
                ('related_purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.purchase', verbose_name='Ref. Compra')),
                ('related_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sale', verbose_name='Ref. Venta')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.warehouse', verbose_name='Bodega Afectada')),
            ],
            options={
                'verbose_name': 'Movimiento de Kardex',
                'verbose_name_plural': 'Kardex (Historial)',
                'ordering': ['-date'],
            },
        ),
    ]
