# Generated by Django 5.2.10 on 2026-02-04 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_purchase_supplier'),
        ('core', '0020_alter_employee_options_remove_employee_is_active_and_more'),
    ]

    operations = [
    ]
