# Generated by Django 5.2.10 on 2026-02-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_company_logo_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
    ]
