# Generated by Django 5.2.10 on 2026-02-08 02:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_company_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'verbose_name': 'Proveedor (Simple)', 'verbose_name_plural': 'Proveedores (Simple)'},
        ),
        migrations.RemoveField(
            model_name='branch',
            name='address',
        ),
        migrations.AddField(
            model_name='branch',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación/Dirección'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='¿Principal?'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_warehouses', to='core.warehouse', verbose_name='Bodega Padre'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.CharField(help_text='Ej: Z9, CENT', max_length=20, verbose_name='Código/Prefijo'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='core.company'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Sucursal'),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_history_legacy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock Físico Global'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cuenta / Referencia / Tarjeta'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre Bodega'),
        ),
    ]
