# Generated by Django 5.2.10 on 2026-02-08 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_provider_options_remove_branch_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='branch',
            name='company_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches_profile', to='core.companyprofile'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='code',
            field=models.CharField(max_length=20, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='Stock Físico'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre Bodega'),
        ),
    ]
