# Generated by Django 5.0.2 on 2026-02-10 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_invoice_invoicedetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='allowed_users',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='currency_symbol',
            field=models.CharField(default='Q', max_length=5, verbose_name='Símbolo Moneda'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre Empresa'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='nit',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='NIT'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono'),
        ),
    ]
