# Generated by Django 5.0.2 on 2026-02-10 02:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_companyprofile_allowed_users_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Marca')),
                ('model', models.CharField(max_length=50, verbose_name='Modelo')),
                ('plate', models.CharField(max_length=20, unique=True, verbose_name='Placa')),
                ('year', models.IntegerField(verbose_name='Año')),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha Emisión')),
                ('provider', models.CharField(max_length=200, verbose_name='Proveedor / Emisor')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='gastos/', verbose_name='Factura (PDF/Foto)')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Caja')),
                ('idp_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IDP (Combustible)')),
                ('base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Base Imponible')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IVA Crédito')),
                ('is_fuel', models.BooleanField(default=False, verbose_name='¿Es Combustible/Vehículo?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vehicle', verbose_name='Vehículo Asignado')),
            ],
        ),
    ]
