# Generated by Django 5.0.2 on 2026-02-10 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_vehicle_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='accounting_entry_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID Partida Contable'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='assigned_driver',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Piloto Responsable'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('TALLER', 'En Mantenimiento'), ('BAJA', 'De Baja')], default='ACTIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='expense',
            name='idp_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='gastos/'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='is_fuel',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='expense',
            name='provider',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='expense',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vehicle'),
        ),
    ]
