# Generated by Django 5.0.2 on 2026-02-10 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_expense_accounting_entry_id_vehicle_assigned_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo/Gasto'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Concepto'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='idp_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='IDP'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='is_fuel',
            field=models.BooleanField(default=False, verbose_name='Es Combustible'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='provider',
            field=models.CharField(max_length=200, verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Factura'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='IVA Crédito'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vehicle', verbose_name='Vehículo (Placa)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='assigned_driver',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Piloto Asignado'),
        ),
    ]
