# Generated by Django 5.0.2 on 2026-02-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_expense_base_amount_alter_expense_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('PENDING', '🟡 Pendiente (Solo Foto)'), ('APPROVED', '🟢 Aprobado y Contabilizado'), ('REJECTED', '🔴 Rechazado')], default='APPROVED', max_length=10),
        ),
    ]
