# Generated by Django 5.0.2 on 2026-02-10 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_expense_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Banco Emisor')),
                ('alias', models.CharField(max_length=100, verbose_name='Alias (Ej: Visa Gerencia)')),
                ('last_4_digits', models.CharField(max_length=4, verbose_name='Últimos 4 dígitos')),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Límite de Crédito')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo Deuda Actual')),
                ('cutoff_day', models.IntegerField(help_text='Día del mes', verbose_name='Día de Corte')),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Efectivo / Caja Chica'), ('CARD', 'Tarjeta de Crédito / Débito'), ('TRANSFER', 'Transferencia Bancaria'), ('CHECK', 'Cheque'), ('CREDIT', 'Crédito (Cuenta por Pagar)')], default='CASH', max_length=20, verbose_name='Método de Pago'),
        ),
        migrations.AddField(
            model_name='expense',
            name='credit_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.creditcard', verbose_name='Tarjeta Usada'),
        ),
    ]
