# Generated by Django 5.0.2 on 2026-02-10 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_creditcard_expense_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='account',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='company',
        ),
        migrations.RemoveField(
            model_name='gasto',
            name='usuario_registra',
        ),
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['code'], 'verbose_name': 'Cuenta Contable', 'verbose_name_plural': 'Nomenclatura Contable'},
        ),
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'Partida Diario', 'verbose_name_plural': 'Libro Diario'},
        ),
        migrations.RemoveField(
            model_name='account',
            name='company',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_selectable',
        ),
        migrations.RemoveField(
            model_name='account',
            name='level',
        ),
        migrations.RemoveField(
            model_name='journalitem',
            name='account_name',
        ),
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Saldo Actual'),
        ),
        migrations.AddField(
            model_name='account',
            name='is_group',
            field=models.BooleanField(default=False, help_text='Marcar si es título de grupo', verbose_name='¿Es Grupo?'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='expense',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entry', to='core.expense', verbose_name='Origen Gasto'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='is_posted',
            field=models.BooleanField(default=False, verbose_name='Asentada (Definitiva)'),
        ),
        migrations.AddField(
            model_name='journalitem',
            name='account',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='core.account', verbose_name='Cuenta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journalitem',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Concepto de Línea'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('PASIVO', 'Pasivo'), ('PATRIMONIO', 'Patrimonio/Capital'), ('INGRESO', 'Ingresos'), ('GASTO', 'Gastos'), ('COSTO', 'Costos de Venta')], max_length=20, verbose_name='Tipo de Cuenta'),
        ),
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Código Cuenta'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre de la Cuenta'),
        ),
        migrations.AlterField(
            model_name='account',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.account', verbose_name='Cuenta Padre'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='accounting_entry_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID Partida (Legacy)'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='gastos/', verbose_name='Factura'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vehicle', verbose_name='Vehículo'),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.product'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='date',
            field=models.DateField(verbose_name='Fecha Contable'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Descripción / Glosa'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='reference',
            field=models.CharField(blank=True, default=0, max_length=100, verbose_name='Referencia (Doc/Fac)'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Fleet',
        ),
        migrations.DeleteModel(
            name='Gasto',
        ),
    ]
