# Generated by Django 5.0.2 on 2026-02-28 07:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=50, unique=True, verbose_name='No. Orden de Compra')),
                ('supplier_name', models.CharField(max_length=150, verbose_name='Proveedor')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de Envío'), ('IN_TRANSIT', 'En Tránsito (Asignada a DUCA)'), ('RECEIVED', 'Recibida en Bodega'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20)),
                ('total_amount_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto Total ($)')),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
            },
        ),
        migrations.CreateModel(
            name='Duca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('duca_number', models.CharField(max_length=50, unique=True, verbose_name='Número de DUCA / Póliza')),
                ('date_acceptance', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Aceptación SAT')),
                ('customs_agent', models.CharField(blank=True, max_length=150, null=True, verbose_name='Agente Aduanero')),
                ('supplier_name', models.CharField(max_length=200, verbose_name='Proveedor (Extranjero)')),
                ('exchange_rate', models.DecimalField(decimal_places=5, default=7.8, max_digits=10, verbose_name='Tipo de Cambio (GTQ/USD)')),
                ('freight_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Flete Total (USD)')),
                ('insurance_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Seguro Total (USD)')),
                ('iva_gtq', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='IVA de Importación (Crédito SAT en Q)')),
                ('other_expenses_gtq', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Otros Gastos (Almacenaje, Tramitador, etc. en Q)')),
                ('status', models.CharField(choices=[('DRAFT', '1. Borrador / En Tránsito'), ('CUSTOMS', '2. En Aduana (Gestión)'), ('LIQUIDATED', '3. Liquidada (Costo calculado)'), ('RECEIVED', '4. Recibida en Bodega'), ('CANCELED', 'Anulada')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('purchase_orders', models.ManyToManyField(blank=True, related_name='ducas', to='imports.purchaseorder', verbose_name='Órdenes de Compra Vinculadas')),
            ],
            options={
                'verbose_name': 'DUCA / Póliza',
                'verbose_name_plural': 'DUCAs / Pólizas',
                'ordering': ['-date_acceptance'],
            },
        ),
        migrations.CreateModel(
            name='DucaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, verbose_name='SKU / Código')),
                ('description', models.CharField(max_length=200, verbose_name='Descripción del Producto')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('fob_unit_usd', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Costo Unitario FOB (USD)')),
                ('dai_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tasa DAI (%)')),
                ('duca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='imports.duca')),
                ('product_catalog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product', verbose_name='Producto en Catálogo (Logística)')),
            ],
            options={
                'verbose_name': 'Producto Importado',
                'verbose_name_plural': 'Productos Importados',
            },
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('FACTORY', '1. En Planta del Proveedor (Extranjero)'), ('DEPARTURE', '2. Salida de Puerto/Aeropuerto Origen'), ('TRANSIT', '3. En Tránsito (Marítimo/Aéreo)'), ('ARRIVAL', '4. Llegada a Puerto en Guatemala (Santo Tomás/Quetzal)'), ('CUSTOMS', '5. En Trámite Aduanal (Retenido/Revisión)'), ('DISPATCHED', '6. Liberado y en Ruta a Bodega Sermaworld')], max_length=20, verbose_name='Tipo de Evento')),
                ('event_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del Evento')),
                ('location', models.CharField(help_text='Ej: Puerto Shenzen, Miami, Puerto Quetzal', max_length=150, verbose_name='Ubicación / Puerto')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observaciones / Novedades')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='imports.duca')),
            ],
            options={
                'verbose_name': 'Evento de Tracking',
                'verbose_name_plural': 'Tracking de Contenedores',
                'ordering': ['-event_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reception_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora de Recepción')),
                ('inventory_processed', models.BooleanField(default=False, verbose_name='Inventario Inyectado al Kardex')),
                ('seal_intact', models.BooleanField(default=True, verbose_name='¿Marchamo de seguridad intacto?')),
                ('condition', models.CharField(default='Excelente - Mercadería en buen estado', max_length=100, verbose_name='Condición de la Carga')),
                ('damages_notes', models.TextField(blank=True, null=True, verbose_name='Notas de Daños o Faltantes')),
                ('integrated_to_inventory', models.BooleanField(default=False, verbose_name='¿Integrado al Kardex?')),
                ('duca', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reception', to='imports.duca', verbose_name='Póliza DUCA')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Recibido por (Bodeguero)')),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.warehouse', verbose_name='Bodega de Destino')),
            ],
            options={
                'verbose_name': 'Recepción de Bodega',
                'verbose_name_plural': 'Recepciones de Bodegas',
            },
        ),
    ]
