# Generated by Django 5.0.2 on 2026-02-25 12:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Duca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('duca_number', models.CharField(max_length=50, unique=True, verbose_name='Número de DUCA / Póliza')),
                ('date_acceptance', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Aceptación SAT')),
                ('customs_agent', models.CharField(blank=True, max_length=150, null=True, verbose_name='Agente Aduanero')),
                ('supplier_name', models.CharField(max_length=200, verbose_name='Proveedor en el Extranjero')),
                ('exchange_rate', models.DecimalField(decimal_places=5, default=7.8, max_digits=10, verbose_name='Tipo de Cambio (BANGUAT)')),
                ('fob_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor FOB (USD)')),
                ('freight_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Flete (USD)')),
                ('insurance_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Seguro (USD)')),
                ('dai_gtq', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='DAI Pagado (Arancel en Q)')),
                ('iva_gtq', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='IVA de Importación (Crédito SAT en Q)')),
                ('other_expenses_gtq', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Otros Gastos (Almacenaje, Tramitador en Q)')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador / En Tránsito'), ('CUSTOMS', 'En Aduana (Gestión)'), ('LIQUIDATED', 'Liquidada (Costeada en Inventario)'), ('CANCELED', 'Anulada')], default='DRAFT', max_length=20, verbose_name='Estado de la Importación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DUCA / Póliza de Importación',
                'verbose_name_plural': 'DUCAs / Pólizas de Importación',
                'ordering': ['-date_acceptance'],
            },
        ),
    ]
