# Generated by Django 5.0.2 on 2026-02-25 13:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Duca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('duca_number', models.CharField(max_length=50, unique=True, verbose_name='Número de DUCA / Póliza')),
                ('date_acceptance', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Aceptación SAT')),
                ('customs_agent', models.CharField(blank=True, max_length=150, null=True, verbose_name='Agente Aduanero')),
                ('supplier_name', models.CharField(max_length=200, verbose_name='Proveedor (Extranjero)')),
                ('exchange_rate', models.DecimalField(decimal_places=5, default=7.8, max_digits=10, verbose_name='Tipo de Cambio (GTQ/USD)')),
                ('freight_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Flete Total (USD)')),
                ('insurance_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Seguro Total (USD)')),
                ('iva_gtq', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='IVA de Importación (Crédito SAT en Q)')),
                ('other_expenses_gtq', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Otros Gastos (Almacenaje, Tramitador, etc. en Q)')),
                ('status', models.CharField(choices=[('DRAFT', '1. Borrador / En Tránsito'), ('CUSTOMS', '2. En Aduana (Gestión)'), ('LIQUIDATED', '3. Liquidada (Costo calculado)'), ('RECEIVED', '4. Recibida en Bodega'), ('CANCELED', 'Anulada')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DUCA / Póliza',
                'verbose_name_plural': 'DUCAs / Pólizas',
                'ordering': ['-date_acceptance'],
            },
        ),
        migrations.CreateModel(
            name='DucaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, verbose_name='SKU / Código')),
                ('description', models.CharField(max_length=200, verbose_name='Descripción del Producto')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('fob_unit_usd', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Costo Unitario FOB (USD)')),
                ('dai_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tasa DAI (%)')),
                ('duca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='imports.duca')),
            ],
            options={
                'verbose_name': 'Producto Importado',
                'verbose_name_plural': 'Productos Importados',
            },
        ),
    ]
