# Generated by Django 5.0.2 on 2026-02-26 01:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('FACTORY', '1. En Planta del Proveedor (Extranjero)'), ('DEPARTURE', '2. Salida de Puerto/Aeropuerto Origen'), ('TRANSIT', '3. En Tránsito (Marítimo/Aéreo)'), ('ARRIVAL', '4. Llegada a Puerto en Guatemala (Santo Tomás/Quetzal)'), ('CUSTOMS', '5. En Trámite Aduanal (Retenido/Revisión)'), ('DISPATCHED', '6. Liberado y en Ruta a Bodega Sermaworld')], max_length=20, verbose_name='Tipo de Evento')),
                ('event_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del Evento')),
                ('location', models.CharField(help_text='Ej: Puerto Shenzen, Miami, Puerto Quetzal', max_length=150, verbose_name='Ubicación / Puerto')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observaciones / Novedades')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('duca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='imports.duca')),
            ],
            options={
                'verbose_name': 'Evento de Tracking',
                'verbose_name_plural': 'Tracking de Contenedores',
                'ordering': ['-event_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseReception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reception_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora de Recepción')),
                ('seal_intact', models.BooleanField(default=True, verbose_name='¿Marchamo de seguridad intacto?')),
                ('condition', models.CharField(default='Excelente - Mercadería en buen estado', max_length=100, verbose_name='Condición de la Carga')),
                ('damages_notes', models.TextField(blank=True, null=True, verbose_name='Notas de Daños o Faltantes')),
                ('integrated_to_inventory', models.BooleanField(default=False, verbose_name='¿Integrado al Kardex?')),
                ('duca', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reception', to='imports.duca', verbose_name='Póliza DUCA')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Recibido por (Bodeguero)')),
            ],
            options={
                'verbose_name': 'Recepción de Bodega',
                'verbose_name_plural': 'Recepciones de Bodegas',
            },
        ),
    ]
