# Generated by Django 5.0.2 on 2026-02-26 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_trackingevent_warehousereception'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=50, unique=True, verbose_name='No. Orden de Compra')),
                ('supplier_name', models.CharField(max_length=150, verbose_name='Proveedor')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de Envío'), ('IN_TRANSIT', 'En Tránsito (Asignada a DUCA)'), ('RECEIVED', 'Recibida en Bodega'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20)),
                ('total_amount_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Monto Total ($)')),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
            },
        ),
        migrations.AddField(
            model_name='duca',
            name='purchase_orders',
            field=models.ManyToManyField(blank=True, related_name='ducas', to='imports.purchaseorder', verbose_name='Órdenes de Compra Vinculadas'),
        ),
    ]
