# Generated by Django 5.0.2 on 2026-02-26 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('imports', '0003_purchaseorder_duca_purchase_orders'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ducaitem',
            name='product_catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product', verbose_name='Producto en Catálogo (Logística)'),
        ),
        migrations.AddField(
            model_name='warehousereception',
            name='inventory_processed',
            field=models.BooleanField(default=False, verbose_name='Inventario Inyectado al Kardex'),
        ),
        migrations.AddField(
            model_name='warehousereception',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.warehouse', verbose_name='Bodega de Destino'),
        ),
    ]
