# Generated by Django 5.0.2 on 2026-02-25 12:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('position', models.CharField(max_length=100, verbose_name='Cargo')),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario Base')),
                ('hiring_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Contratación')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Pago')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_closed', models.BooleanField(default=False, verbose_name='Cerrada')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
