# Generated by Django 5.0.2 on 2026-02-12 02:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='company',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='payrolldetail',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='payrolldetail',
            name='payroll',
        ),
        migrations.RenameField(
            model_name='payroll',
            old_name='total_amount',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='dpi',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='incentive_bonus',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='is_finalized',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='start_date',
        ),
        migrations.AddField(
            model_name='employee',
            name='hiring_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Contratación'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Pago'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Cerrada'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Empresa'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
        migrations.DeleteModel(
            name='PayrollDetail',
        ),
    ]
