# Generated by Django 5.0.2 on 2026-04-26 07:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLoanAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Solicitud')),
                ('loan_type', models.CharField(choices=[('ANTICIPO', 'Anticipo'), ('PRESTAMO', 'Préstamo')], max_length=20, verbose_name='Tipo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo')),
                ('installments', models.PositiveIntegerField(default=1, verbose_name='Cuotas')),
                ('status', models.CharField(choices=[('ACTIVO', 'Activo'), ('CANCELADO', 'Cancelado')], default='ACTIVO', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_advances', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Anticipo/Préstamo a Empleado',
                'verbose_name_plural': 'Anticipos y Préstamos a Empleados',
                'ordering': ['-request_date', '-id'],
            },
        ),
    ]
