# Generated by Django 5.0.2 on 2026-05-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_payrollrun_employeepayrollline'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeloanadvance',
            name='paid_installments',
            field=models.PositiveIntegerField(default=0, verbose_name='Cuotas Pagadas'),
        ),
    ]
