# Generated by Django 5.0.2 on 2026-02-25 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_companies',
            field=models.ManyToManyField(blank=True, help_text='Selecciona a qué empresas puede acceder este usuario.', related_name='allowed_users', to='core.company', verbose_name='Empresas Permitidas'),
        ),
        migrations.AddField(
            model_name='user',
            name='current_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_working_here', to='core.company', verbose_name='Trabajando actualmente en'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='anaira_user_groups', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='anaira_user_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
