# Generated by Django 5.2.10 on 2026-01-29 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0002_gasto_amount_untaxed_gasto_iva_fleet_gasto_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_working_here', to='core.company', verbose_name='Trabajando actualmente en'),
        ),
    ]
