# Generated by Django 5.0.2 on 2026-02-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_companies',
            field=models.ManyToManyField(blank=True, help_text='Selecciona a qué empresas puede acceder este usuario.', related_name='allowed_users', to='core.company', verbose_name='Empresas Permitidas'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('STAFF', 'Staff'), ('MANAGER', 'Gerencia'), ('ANALYST', 'Analista'), ('VIEWER', 'Consulta')], default='VIEWER', help_text='Rol dentro de Anaira ERP', max_length=20),
        ),
    ]
