# Generated by Django 5.0.2 on 2026-02-11 21:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Cantidad')),
                ('movement_type', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida'), ('ADJ', 'Ajuste'), ('TRF', 'Transferencia')], max_length=3, verbose_name='Tipo de Movimiento')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo/Referencia')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Empresa')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Producto')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.warehouse', verbose_name='Bodega')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
