# Generated by Django 5.0.2 on 2026-02-11 21:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_journalitem_account_and_more'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='category',
            name='company',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='movementdetail',
            name='movement',
        ),
        migrations.RemoveField(
            model_name='movementdetail',
            name='product',
        ),
        migrations.RemoveField(
            model_name='movementdetail',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='product',
            name='company',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='product',
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Producto'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='stock',
            name='warehouse',
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={},
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='description',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='user',
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo/Referencia'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida'), ('ADJ', 'Ajuste'), ('TRF', 'Transferencia')], max_length=3, verbose_name='Tipo de Movimiento'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='warehouse',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.warehouse', verbose_name='Bodega'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='MovementDetail',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
