# Generated by Django 5.0.2 on 2026-02-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Código Contable')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Cuenta')),
                ('account_type', models.CharField(choices=[('ASSET', 'Activo'), ('LIABILITY', 'Pasivo'), ('EQUITY', 'Patrimonio/Capital'), ('INCOME', 'Ingresos'), ('EXPENSE', 'Gastos')], max_length=20)),
                ('is_group', models.BooleanField(default=False, verbose_name='Es cuenta agrupadora')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha Contable')),
                ('description', models.TextField(verbose_name='Concepto/Descripción')),
                ('reference', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JournalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('debit', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Debe')),
                ('credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Haber')),
            ],
        ),
    ]
