# Generated by Django 5.0.2 on 2026-02-16 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50)),
                ('currency', models.CharField(choices=[('GTQ', 'Quetzales'), ('USD', 'Dólares')], default='GTQ', max_length=3)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.CharField(choices=[('IN', 'Depósito / Ingreso'), ('OUT', 'Retiro / Cheque / Transferencia')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('receipt_image', models.ImageField(upload_to='expenses_receipts/', verbose_name='Foto Factura')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente de Revisión'), ('APPROVED', 'Contabilizado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=20)),
                ('provider_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Proveedor')),
                ('provider_nit', models.CharField(blank=True, max_length=20, null=True, verbose_name='NIT')),
                ('invoice_series', models.CharField(blank=True, max_length=20, null=True, verbose_name='Serie')),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='No. Factura')),
                ('description', models.TextField(verbose_name='Descripción del Gasto')),
                ('suggested_account', models.CharField(default='Gastos Generales', max_length=100, verbose_name='Cuenta Contable Sugerida')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Factura')),
                ('tax_base', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Base Imponible')),
                ('tax_iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='IVA Crédito')),
                ('tax_idp', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Impuesto IDP')),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=255, verbose_name='Concepto')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='JournalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('debit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('line', models.CharField(max_length=50)),
                ('plate', models.CharField(max_length=20)),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
