# Generated by Django 5.0.2 on 2026-02-27 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Latitud GPS'),
        ),
        migrations.AddField(
            model_name='expense',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Longitud GPS'),
        ),
        migrations.AddField(
            model_name='expense',
            name='pump_image',
            field=models.ImageField(blank=True, null=True, upload_to='expenses_pumps/', verbose_name='Foto de la Bomba'),
        ),
    ]
