# Generated by Django 5.0.2 on 2026-02-28 07:54

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banktransaction',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.RenameField(
            model_name='banktransaction',
            old_name='bank_account',
            new_name='account',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='banktransaction',
            name='company',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='account_name',
            field=models.CharField(default='General', max_length=100, verbose_name='Nombre de la Cuenta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo Inicial al 1 de Enero'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 2, 28, 7, 53, 23, 823704, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='registered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(max_length=50, verbose_name='Número de Cuenta'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(max_length=100, verbose_name='Nombre del Banco (Ej. Banrural, BI)'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='core.company'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='currency',
            field=models.CharField(choices=[('GTQ', 'Quetzales (Q)'), ('USD', 'Dólares ($)')], default='GTQ', max_length=3),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='date',
            field=models.DateField(verbose_name='Fecha del Movimiento'),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='description',
            field=models.TextField(verbose_name='Concepto detallado'),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='reference',
            field=models.CharField(default='S/N', max_length=100, verbose_name='No. de Boleta / Cheque / Transferencia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Depósito / Ingreso'), ('WITHDRAWAL', 'Retiro / Cheque / Gasto')], max_length=15),
        ),
    ]
