# Generated by Django 5.0.2 on 2026-02-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='provider_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre del Proveedor'),
        ),
    ]
