# Generated by Django 5.0.2 on 2026-02-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='origin',
            field=models.CharField(choices=[('PILOT', 'App Piloto'), ('SCANNER', 'Smart Scanner IA'), ('MANUAL', 'Ingreso Manual')], default='MANUAL', max_length=20),
        ),
    ]
