# Generated by Django 5.0.2 on 2026-03-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_banktransaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('EFECTIVO', '💵 Efectivo'), ('TARJETA', '💳 Tarjeta de Crédito / Débito')], default='EFECTIVO', max_length=20, verbose_name='¿Cómo se pagó?'),
        ),
    ]
