# Generated by Django 5.0.2 on 2026-02-11 22:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_expense'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalitem',
            name='account',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='company',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='journalitem',
            name='entry',
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Nombre del Banco')),
                ('account_number', models.CharField(max_length=50, verbose_name='Número de Cuenta')),
                ('currency', models.CharField(default='GTQ', max_length=3, verbose_name='Moneda')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Saldo Actual')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('transaction_type', models.CharField(choices=[('IN', 'Depósito (Entrada)'), ('OUT', 'Retiro/Cheque (Salida)')], max_length=3, verbose_name='Tipo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('reference', models.CharField(max_length=100, verbose_name='Referencia/Boleta')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.bankaccount', verbose_name='Cuenta Bancaria')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='JournalEntry',
        ),
        migrations.DeleteModel(
            name='JournalItem',
        ),
    ]
