# Generated by Django 5.0.2 on 2026-02-22 21:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_expense_origin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='conductores',
            field=models.ManyToManyField(blank=True, help_text='Selecciona los usuarios que manejan este vehículo.', related_name='vehiculos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Pilotos Asignados'),
        ),
    ]
