# Generated by Django 5.0.2 on 2026-02-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_expense_latitude_expense_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='assistant_ok',
            field=models.BooleanField(default=False, verbose_name='VoBo. Asistente'),
        ),
        migrations.AddField(
            model_name='expense',
            name='supervisor_1_ok',
            field=models.BooleanField(default=False, verbose_name='VoBo. Supervisor 1'),
        ),
        migrations.AddField(
            model_name='expense',
            name='supervisor_2_ok',
            field=models.BooleanField(default=False, verbose_name='VoBo. Supervisor 2'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('PRE_REVIEW', 'Filtro de Supervisores'), ('PENDING', 'Pendiente de Revisión'), ('APPROVED', 'Contabilizado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=20),
        ),
    ]
