# Generated by Django 5.0.2 on 2026-02-16 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_journalentry_journalitem'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='No. Factura'),
        ),
        migrations.AddField(
            model_name='expense',
            name='invoice_series',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Serie'),
        ),
        migrations.AddField(
            model_name='expense',
            name='provider_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='expense',
            name='provider_nit',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='NIT'),
        ),
        migrations.AddField(
            model_name='expense',
            name='suggested_account',
            field=models.CharField(default='Gastos Generales', max_length=100, verbose_name='Cuenta Contable Sugerida'),
        ),
        migrations.AddField(
            model_name='expense',
            name='tax_base',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Base Imponible'),
        ),
        migrations.AddField(
            model_name='expense',
            name='tax_idp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Impuesto IDP'),
        ),
        migrations.AddField(
            model_name='expense',
            name='tax_iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='IVA Crédito'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(verbose_name='Descripción del Gasto'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='receipt_image',
            field=models.ImageField(default=0, upload_to='expenses_receipts/', verbose_name='Foto Factura'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente de Revisión'), ('APPROVED', 'Contabilizado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='expense',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Factura'),
        ),
    ]
