# Generated by Django 5.0.2 on 2026-03-01 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_expense_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre/Marca')),
                ('placa', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GastoOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('tipo_gasto', models.CharField(choices=[('combustible', 'Combustible'), ('repuestos', 'Repuestos'), ('mantenimiento', 'Mantenimiento')], default='combustible', max_length=20)),
                ('payment_method', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta (Crédito/Débito)')], default='EFECTIVO', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('receipt_image', models.ImageField(upload_to='gastos/facturas/')),
                ('pump_image', models.ImageField(blank=True, null=True, upload_to='gastos/bombas/')),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(choices=[('En_Supervision', 'En Supervisión'), ('Pendiente_Contabilidad', 'Pendiente Contabilidad'), ('Rechazado', 'Rechazado')], default='En_Supervision', max_length=50)),
                ('supervisor_1_ok', models.BooleanField(default=False)),
                ('supervisor_2_ok', models.BooleanField(default=False)),
                ('assistant_ok', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.vehiculo')),
            ],
        ),
    ]
