# Generated by Django 5.0.2 on 2026-02-11 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_remove_journalitem_account_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Marca')),
                ('model', models.CharField(max_length=50, verbose_name='Modelo')),
                ('plate', models.CharField(max_length=20, verbose_name='Placa/Matrícula')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Año')),
                ('color', models.CharField(blank=True, max_length=30, null=True, verbose_name='Color')),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Piloto Asignado')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='Empresa')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.vehicle', verbose_name='Vehículo (Opcional)'),
        ),
    ]
