# Generated by Django 5.0.2 on 2026-02-23 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_vehicle_conductores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código NIIF')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de la Cuenta')),
                ('account_type', models.CharField(choices=[('ASSET', 'Activo'), ('LIABILITY', 'Pasivo'), ('EQUITY', 'Patrimonio'), ('REVENUE', 'Ingresos'), ('EXPENSE', 'Gastos')], max_length=15)),
                ('is_transactional', models.BooleanField(default=True, verbose_name='Acepta Movimientos')),
            ],
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='description',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='expense_ref',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='total',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='concept',
            field=models.CharField(default='2026-01-01 00:00:00', max_length=255, verbose_name='Concepto General'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journalentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2026-01-01 00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journalentry',
            name='is_opening_balance',
            field=models.BooleanField(default=False, verbose_name='Es Asiento de Apertura'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='date',
            field=models.DateField(default='2026-01-01', verbose_name='Fecha de Partida'),
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Debe')),
                ('credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Haber')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.account', verbose_name='Cuenta Contable')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry')),
            ],
        ),
    ]
