# Generated by Django 5.0.2 on 2026-03-02 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_bankaccount_balance'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Banco Emisor (Ej. Promerica, BAC)')),
                ('card_name', models.CharField(max_length=100, verbose_name='Nombre en la Tarjeta (Ej. Visa Flotilla 1)')),
                ('last_four_digits', models.CharField(max_length=4, verbose_name='Últimos 4 dígitos')),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Límite de Crédito')),
                ('cutoff_day', models.IntegerField(verbose_name='Día de Corte (1-31)')),
                ('payment_day', models.IntegerField(verbose_name='Día de Pago (1-31)')),
                ('current_debt', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Deuda Actual (Saldo Consumido)')),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to='core.company')),
            ],
        ),
    ]
