# Generated by Django 5.0.2 on 2026-03-02 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_creditcard'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPayable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=200, verbose_name='Nombre del Proveedor')),
                ('invoice_number', models.CharField(max_length=100, verbose_name='No. de Factura / Recibo')),
                ('description', models.TextField(verbose_name='Concepto de la Deuda')),
                ('issue_date', models.DateField(verbose_name='Fecha de Emisión')),
                ('due_date', models.DateField(verbose_name='Fecha de Vencimiento límite')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Total Original')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Saldo Pendiente Actual')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('PARCIAL', 'Pago Parcial'), ('PAGADO', 'Pagado / Liquidado')], default='PENDIENTE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_payable', to='core.company')),
            ],
        ),
    ]
