# Generated by Django 5.0.2 on 2026-03-03 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_accountpayable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastooperativo',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.vehicle'),
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
    ]
