# Generated by Django 5.0.2 on 2026-05-02 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='invoice_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Factura'),
        ),
    ]
