# Generated by Django 5.0.2 on 2026-02-28 07:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre / Razón Social')),
                ('nit', models.CharField(blank=True, max_length=20, null=True, verbose_name='NIT')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('client_type', models.CharField(choices=[('RETAIL', 'Consumidor Final'), ('WHOLESALE', 'Mayorista / Distribuidor')], default='RETAIL', max_length=20, verbose_name='Tipo de Cliente')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Límite de Crédito (Q)')),
                ('is_blacklisted', models.BooleanField(default=False, verbose_name='En Libro Negro (Moroso)')),
                ('blacklist_reason', models.TextField(blank=True, null=True, verbose_name='Motivo de Bloqueo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CRMInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CALL', 'Llamada Telefónica'), ('EMAIL', 'Correo Electrónico'), ('MEETING', 'Reunión Presencial'), ('WHATSAPP', 'Mensaje WhatsApp')], max_length=20, verbose_name='Tipo de Contacto')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
                ('notes', models.TextField(verbose_name='Minuta / Notas de la reunión')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='sales.client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Válida hasta')),
                ('notes', models.TextField(blank=True, verbose_name='Condiciones / Notas')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador / Cotización'), ('SENT', 'Enviada al Cliente'), ('APPROVED', 'Pedido de Venta (Aprobado)'), ('INVOICED', 'Facturada y Despachada'), ('CANCELED', 'Anulada')], default='DRAFT', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.client', verbose_name='Cliente')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
                ('warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.warehouse', verbose_name='Bodega Origen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Unitario')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Descuento (%)')),
                ('total_line', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.quotation')),
            ],
        ),
        migrations.CreateModel(
            name='SaleInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Factura')),
                ('serie', models.CharField(default='A', max_length=10, verbose_name='Serie')),
                ('invoice_number', models.CharField(max_length=50, verbose_name='Número de Factura')),
                ('client_nit', models.CharField(default='CF', max_length=15, verbose_name='NIT del Cliente')),
                ('client_name', models.CharField(default='Consumidor Final', max_length=200, verbose_name='Nombre del Cliente')),
                ('tax_base', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Base Imponible')),
                ('tax_iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='IVA (Débito)')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Factura')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador / Pendiente'), ('APPROVED', 'Factura Emitida (FEL)'), ('CANCELED', 'Anulada')], default='DRAFT', max_length=15)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
