# Generated by Django 5.0.2 on 2026-02-27 00:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CALL', 'Llamada Telefónica'), ('EMAIL', 'Correo Electrónico'), ('MEETING', 'Reunión Presencial'), ('WHATSAPP', 'Mensaje WhatsApp')], max_length=20, verbose_name='Tipo de Contacto')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
                ('notes', models.TextField(verbose_name='Minuta / Notas de la reunión')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaleInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Factura')),
                ('serie', models.CharField(default='A', max_length=10, verbose_name='Serie')),
                ('invoice_number', models.CharField(max_length=50, verbose_name='Número de Factura')),
                ('client_nit', models.CharField(default='CF', max_length=15, verbose_name='NIT del Cliente')),
                ('client_name', models.CharField(default='Consumidor Final', max_length=200, verbose_name='Nombre del Cliente')),
                ('tax_base', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Base Imponible')),
                ('tax_iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='IVA (Débito)')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Factura')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador / Pendiente'), ('APPROVED', 'Factura Emitida (FEL)'), ('CANCELED', 'Anulada')], default='DRAFT', max_length=15)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.AddField(
            model_name='client',
            name='blacklist_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de Bloqueo'),
        ),
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('RETAIL', 'Consumidor Final'), ('WHOLESALE', 'Mayorista / Distribuidor')], default='RETAIL', max_length=20, verbose_name='Tipo de Cliente'),
        ),
        migrations.AddField(
            model_name='client',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Límite de Crédito (Q)'),
        ),
        migrations.AddField(
            model_name='client',
            name='is_blacklisted',
            field=models.BooleanField(default=False, verbose_name='En Libro Negro (Moroso)'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Condiciones / Notas'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador / Cotización'), ('SENT', 'Enviada al Cliente'), ('APPROVED', 'Pedido de Venta (Aprobado)'), ('INVOICED', 'Facturada y Despachada'), ('CANCELED', 'Anulada')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Válida hasta'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.warehouse', verbose_name='Bodega Origen'),
        ),
        migrations.AddField(
            model_name='crminteraction',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='sales.client'),
        ),
        migrations.AddField(
            model_name='crminteraction',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.AddField(
            model_name='crminteraction',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
        ),
    ]
