# Generated by Django 5.0.2 on 2026-02-25 04:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Factura')),
                ('serie', models.CharField(default='A', max_length=10, verbose_name='Serie')),
                ('invoice_number', models.CharField(max_length=50, verbose_name='Número de Factura')),
                ('client_nit', models.CharField(default='CF', max_length=15, verbose_name='NIT del Cliente')),
                ('client_name', models.CharField(default='Consumidor Final', max_length=200, verbose_name='Nombre del Cliente')),
                ('tax_base', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Base Imponible')),
                ('tax_iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='IVA (Débito)')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Factura')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador / Pendiente'), ('APPROVED', 'Aprobada / Contabilizada'), ('CANCELED', 'Anulada')], default='DRAFT', max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('SENT', 'Enviada'), ('INVOICED', 'Facturada'), ('CANCELED', 'Anulada')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.warehouse', verbose_name='Bodega'),
        ),
    ]
