# Generated by Django 5.0.2 on 2026-02-27 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_crminteraction_saleinvoice_delete_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Descuento (%)'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Unitario'),
        ),
    ]
